language: python
python:
    - 3.5

services:
    - redis-server
before_install:
    - redis-server --port 6380 &
    - python3.5 ./tests/server.py &

install: 
    -  pip install .
    -  "pip install -r requirements.txt"
    -  pip install flake8
    -  pip install coveralls 
before_script:
    flake8 .

script:
    coverage run --source=groups -m py.test
after_success:
    coveralls
